# Generated by Django 6.0.2 on 2026-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('show_news', models.BooleanField(default=False, verbose_name='show news')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-date_creation'],
            },
        ),
    ]
