# Generated by Django 6.0.2 on 2026-03-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='News',
        ),
    ]
