# Generated by Django 6.0.3 on 2026-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_noticia_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='show_news',
            field=models.BooleanField(default=False, verbose_name='mostrar noticia'),
        ),
    ]
