# Generated by Django 5.0 on 2026-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
