# Generated by Django 6.0.2 on 2026-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('age', models.IntegerField(default=18, help_text='Introduce tu edad en formato numerico', verbose_name='Edad')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
            ],
        ),
    ]
