# Generated by Django 6.0.2 on 2026-02-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Curso')),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('calification', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='todos.Register', to='todos.student'),
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_registration'),
        ),
    ]
