# Generated by Django 6.0.2 on 2026-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('show_course', models.BooleanField(default=False, verbose_name='mostrar curso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-date_creation'],
            },
        ),
    ]
