# Generated by Django 6.0.2 on 2026-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='topics',
            field=models.FileField(blank=True, null=True, upload_to='tempario/pdf/'),
        ),
    ]
