# Generated by Django 6.0.3 on 2026-03-05 14:45

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='main_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
