# Generated by Django 5.0 on 2026-03-05 16:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
